kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: {'stderr_lines': [], u'changed': True, u'end': u'2018-01-22 11:32:07.230060', 'failed': False, u'stdout': u'jvSuzbqG+oeZSjKlTlFoBV7NZrRL4+ZyLUsgwAedbLY=', u'cmd': u'echo $(head -c 32 /dev/urandom | base64)', u'rc': 0, u'start': u'2018-01-22 11:32:07.218730', u'stderr': u'', u'delta': u'0:00:00.011330', 'stdout_lines': [u'jvSuzbqG+oeZSjKlTlFoBV7NZrRL4+ZyLUsgwAedbLY=']}
      - identity: {}