- name: Push etcd tar to etcd node
  synchronize:
    mode: push
    src: roles/etcd/files/etcd-v3.2.14-linux-arm64.tar.gz
    dest: /home/kubernetes

- name: Unpack etcd
  shell: tar -xzf /home/kubernetes/etcd-v3.2.14-linux-arm64.tar.gz